### PR TITLE
Kicad files for Plinky v3; added testpoints and fixed Testjig

### PR DESCRIPTION
**Pull request by makingsoundmachines**
v3 Kicad Files for Plinky, last revision by Enrica / Making Sound Machines, based on the fixes and contributions by TiNRS, LPZW, Okyeron.

This is the previous work-in-progress version [plinkyblack_hwmidi_jacks](https://github.com/makingsoundmachines/plinky_public/tree/main/hw/plinkyblack_hwmidi_jacks), with additional Test points at the +/-12V pin header and for the now SMD audio jacks at the top.

The idea is to eventually retire the intermediate steps
[plinkyblack_hwmidi](https://github.com/makingsoundmachines/plinky_public/tree/main/hw/plinkyblack_hwmidi)
[plinkyblack_hwmidi_jacks](https://github.com/makingsoundmachines/plinky_public/tree/main/hw/plinkyblack_hwmidi_jacks)

The jig has been updated to match these changes, including new gerber files and parts list, and is tested working with the v3 version above. Old gerber files have been removed from the testjig project.

### CODE REVIEW

**Comment by makingsoundmachines** [comment]
Added small update to main.c: 
Set UART3 baud rate to 31250 (MIDI baud rate)

It was still set to 115200 from printf debugging.

**Comment by okyeron** [comment]
Should we delete a bunch of the kicad backup zip files?

`hw/v3/plinkyblack-backups/`
`hw/v3/plinkyblack_hwmidi-backups/`
`hw/v3/plinkyblack_hwmidi_jacks/`

?

**Comment by makingsoundmachines** [comment]
> Should we delete a bunch of the kicad backup zip files?
> 
> `hw/v3/plinkyblack-backups/` `hw/v3/plinkyblack_hwmidi-backups/` `hw/v3/plinkyblack_hwmidi_jacks/`

Good call, removed the backup files from the pull request.

**Comment by mmalex** [comment]
great stuff! there's a .lck file and maybe some other kicad detritis but I think we can clean that up later. since this is mostly additions, lets move forward and get this in. nice one! thanks for adding all the kicad mod files too

**Pull request merged**
